# Generated by Django 2.2 on 2020-06-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Contratante',
                'verbose_name_plural': 'Contratantes',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=1, null=True)),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título')),
                ('documento', models.FileField(null=True, upload_to='documento_publico/%Y/%m/%d', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Documento Pessoal do Usuario',
                'verbose_name_plural': 'Documentos Pessoais dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='PoloAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Adicione o endereço/telefones, horário de funcionamento', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Polo de Atuação',
                'verbose_name_plural': 'Polos de Atuações',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=240, null=True, verbose_name='Título')),
                ('codigo', models.CharField(max_length=250, unique=True, verbose_name='Código')),
                ('polo_atuacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PoloAtuacao', verbose_name='Polo de atuação')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Documento')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Servico', verbose_name='Documento Requisitado')),
            ],
            options={
                'verbose_name': 'Documento Requisitado',
                'verbose_name_plural': 'Documentos Requisitados',
            },
        ),
    ]
