# Generated by Django 2.2 on 2020-06-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0019_remove_edital_servicos'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='edital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edital.Edital', verbose_name='Edital'),
        ),
    ]
