# Generated by Django 2.2 on 2020-06-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='edital',
        ),
    ]
