# Generated by Django 2.2 on 2020-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documento_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='edital',
        ),
    ]
