# Generated by Django 2.2 on 2020-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_requisito_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='edital',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='polo_atuacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='title',
        ),
        migrations.AddField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=240, null=True, unique=True, verbose_name='Título'),
        ),
    ]
