# Generated by Django 2.2 on 2020-06-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servico_documento_requisito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='documento_requisito',
        ),
        migrations.AddField(
            model_name='servico',
            name='requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Requisito', verbose_name='Documento Requisitado'),
        ),
    ]
