# Generated by Django 2.2 on 2020-06-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200613_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='requisito',
        ),
        migrations.AddField(
            model_name='requisito',
            name='requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Servico', verbose_name='Documento Requisitado'),
        ),
    ]
