# Generated by Django 2.2 on 2020-06-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200613_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisito',
            options={'verbose_name': 'Documento Requisitado', 'verbose_name_plural': 'Documentos Requisitados'},
        ),
        migrations.RemoveField(
            model_name='requisito',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='requisito',
            name='ordem',
        ),
        migrations.AddField(
            model_name='requisito',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Documento'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='titulo',
            field=models.CharField(max_length=250, null=True, verbose_name='Título do Documento'),
        ),
    ]
