# Generated by Django 2.2 on 2020-06-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200613_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisito',
            old_name='requisito',
            new_name='servico',
        ),
    ]
