# Generated by Django 2.2 on 2020-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200613_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='codigo',
            field=models.CharField(max_length=250, null=True, verbose_name='Código'),
        ),
    ]
