# Generated by Django 2.2 on 2020-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servico_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='codigo',
            field=models.CharField(default='S/C', max_length=250, verbose_name='Código'),
        ),
    ]
