# Generated by Django 2.2 on 2020-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200616_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='codigo',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Código do Documento'),
        ),
    ]
