# Generated by Django 2.2 on 2020-06-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200616_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='codigo',
        ),
    ]
