# Generated by Django 2.2 on 2020-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_documento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='titulo',
            field=models.CharField(max_length=250, null=True, verbose_name='Título do Documento'),
        ),
    ]
