# Generated by Django 2.2 on 2020-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='codigo',
            field=models.CharField(max_length=250, unique=True, verbose_name='Código'),
        ),
    ]
