# Generated by Django 2.2 on 2020-06-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200616_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=1, null=True)),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título')),
                ('documento', models.FileField(null=True, upload_to='documento_publico/%Y/%m/%d', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento do Usuario',
                'verbose_name_plural': 'Documentos do Usuários',
            },
        ),
    ]
