# Generated by Django 2.2 on 2020-06-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_documentousuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentousuario',
            options={'verbose_name': 'Documento Pessoal do Usuario', 'verbose_name_plural': 'Documentos Pessoais dos Usuários'},
        ),
        migrations.RemoveField(
            model_name='documentousuario',
            name='documento',
        ),
    ]
