# Generated by Django 2.2 on 2020-06-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200619_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentousuario',
            name='ordem',
        ),
    ]
