# Generated by Django 2.2 on 2020-06-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_documentousuario_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='polo_atuacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PoloAtuacao', verbose_name='Polo de atuação'),
        ),
    ]
