# Generated by Django 2.2 on 2020-05-28 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativar essa Conta ?')),
                ('nome', models.CharField(max_length=150, null=True, verbose_name='* Nome')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='* CPF')),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='* Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True, verbose_name='* Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='* CNPJ')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='* Cpf do Responsável')),
                ('cnpj_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='* Nome do Responsável')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('telefone', models.CharField(max_length=20, verbose_name='* Telefone')),
                ('endereco', models.CharField(max_length=100, verbose_name='* Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='* Número')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50, verbose_name='* Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='* Cidade')),
                ('cep', models.CharField(max_length=20, verbose_name='* Cep')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande Do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='* Estado')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de acesso')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
