# Generated by Django 2.2 on 2020-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='* E-mail'),
        ),
    ]
