# Generated by Django 2.2 on 2020-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Feminino'), ('0', 'Masculino')], max_length=1, null=True),
        ),
    ]
