# Generated by Django 2.2 on 2020-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200610_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_pessoa',
            field=models.CharField(choices=[('0', 'Pessoa Física'), ('1', 'Pessoa Jurídica')], max_length=1, null=True),
        ),
    ]
