# Generated by Django 2.2 on 2020-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_categoria_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cpf do Responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cnpj_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande Do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, default='S/N', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('0', 'Masculino'), ('1', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
