# Generated by Django 2.2 on 2020-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200611_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Feminino'), ('0', 'Masculino')], max_length=1, null=True),
        ),
    ]
