# Generated by Django 2.2 on 2020-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_auto_20200615_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('0', 'Masculino'), ('1', 'Feminino')], default='0', max_length=1, null=True),
        ),
    ]
