# Generated by Django 2.2 on 2020-06-22 14:38

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Rascunho'), ('1', 'Publicado'), ('2', 'Cancelado'), ('3', 'Encerrado')], default='0', max_length=30)),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título')),
                ('codigo', models.CharField(max_length=250, null=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('0', 'Pessoa Física'), ('1', 'Pessoa Jurídica'), ('2', 'Pessoa Física/Jurídica')], max_length=60, verbose_name='Categoria')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de Publicação')),
                ('ano_publicacao', models.CharField(blank=True, editable=False, max_length=5, null=True, verbose_name='Ano de Publicação')),
                ('inicio_inscricao', models.DateTimeField(verbose_name='Inicio das Inscrições')),
                ('fim_inscricao', models.DateTimeField(verbose_name='Fim das Inscrições')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('contratante', models.ManyToManyField(related_query_name='+', to='core.Contratante')),
                ('documentos_usuario', models.ManyToManyField(related_query_name='+', to='core.DocumentoUsuario')),
                ('servicos', models.ManyToManyField(blank=True, related_query_name='+', to='core.Servico')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Inabilitada'), ('2', 'Habilitada'), ('3', 'Expirada'), ('4', 'Descredenciada')], default='0', max_length=100, verbose_name='Status geral')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital.Edital')),
                ('servicos', models.ManyToManyField(to='core.Servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='DocumentoUsuarioInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Documento OK'), ('2', 'Documento Vencido'), ('3', 'Documento Ilegível'), ('4', 'Documento Inválido')], default='0', max_length=100, verbose_name='Status do Documento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('documento', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('documento_usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DocumentoUsuario')),
                ('inscricao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edital.Inscricao')),
            ],
            options={
                'verbose_name': 'Documento Pessoal do Usuário',
                'verbose_name_plural': 'Documentos Pessoais dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRequisitoInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Documento OK'), ('2', 'Documento Vencido'), ('3', 'Documento Ilegível'), ('4', 'Documento Inválido')], default='0', max_length=100, verbose_name='Status do Documento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('documento', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('inscricao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edital.Inscricao')),
                ('requisito', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Requisito')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Servico')),
            ],
            options={
                'verbose_name': 'Documento Requisitado',
                'verbose_name_plural': 'Documentos Requisitados',
            },
        ),
    ]
