# Generated by Django 2.2 on 2020-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='codigo',
            field=models.CharField(max_length=250, null=True, verbose_name='Código'),
        ),
    ]
