# Generated by Django 2.2 on 2020-05-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0003_auto_20200529_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('0', 'Rascunho'), ('1', 'Publicado'), ('2', 'Cancelado'), ('3', 'Encerrado')], default='0', max_length=30),
        ),
    ]
