# Generated by Django 2.2 on 2020-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0005_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=250, null=True, verbose_name='Título'),
        ),
    ]
