# Generated by Django 2.2 on 2020-05-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0006_documento_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.AddField(
            model_name='edital',
            name='ano_publicacao',
            field=models.DateTimeField(null=True, verbose_name='Ano de Publicação'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(null=True, upload_to='documento_publico/%Y/%m/%d', verbose_name='Documento'),
        ),
    ]
