# Generated by Django 2.2 on 2020-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0008_auto_20200531_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='ano_publicacao',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, verbose_name='Ano de Publicação'),
        ),
    ]
