# Generated by Django 2.2 on 2020-06-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0009_auto_20200609_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=1, null=True)),
                ('titulo', models.CharField(max_length=250, null=True, verbose_name='Título')),
                ('edital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edital.Edital', verbose_name='Edital')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
    ]
