# Generated by Django 2.2 on 2020-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0010_requisito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Contratante',
                'verbose_name_plural': 'Contratantes',
            },
        ),
        migrations.CreateModel(
            name='PoloAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(help_text='Adicione o endereço/telefones, horário de funcionamento', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Polo de Atuação',
                'verbose_name_plural': 'Polos de Atuações',
            },
        ),
        migrations.AddField(
            model_name='edital',
            name='contratante',
            field=models.ManyToManyField(related_query_name='+', to='edital.Contratante'),
        ),
        migrations.AddField(
            model_name='edital',
            name='polo_atuacao',
            field=models.ManyToManyField(related_query_name='+', to='edital.PoloAtuacao'),
        ),
    ]
