# Generated by Django 2.2 on 2020-06-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0011_auto_20200610_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratante',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='poloatuacao',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='poloatuacao',
            old_name='name',
            new_name='nome',
        ),
    ]
