# Generated by Django 2.2 on 2020-06-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0014_remove_requisito_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=240, null=True, unique=True, verbose_name='Título')),
                ('polo_atuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edital.PoloAtuacao', verbose_name='Polo de atuação')),
            ],
        ),
    ]
