# Generated by Django 2.2 on 2020-06-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0015_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='edital',
        ),
        migrations.RemoveField(
            model_name='requisito',
            name='edital',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='polo_atuacao',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='contratante',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='polo_atuacao',
        ),
        migrations.DeleteModel(
            name='Contratante',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='PoloAtuacao',
        ),
        migrations.DeleteModel(
            name='Requisito',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
