# Generated by Django 2.2 on 2020-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('edital', '0017_edital_contratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='polo_atuacao',
            field=models.ManyToManyField(related_query_name='+', to='core.PoloAtuacao'),
        ),
        migrations.AddField(
            model_name='edital',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='core.Servico'),
        ),
    ]
