# Generated by Django 2.2 on 2020-06-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0018_auto_20200613_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='servicos',
        ),
    ]
