# Generated by Django 2.2 on 2020-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documento_edital'),
        ('edital', '0019_remove_edital_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='servicos',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='+', to='core.Servico'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='contratante',
            field=models.ManyToManyField(null=True, related_query_name='+', to='core.Contratante'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='polo_atuacao',
            field=models.ManyToManyField(null=True, related_query_name='+', to='core.PoloAtuacao'),
        ),
    ]
