# Generated by Django 2.2 on 2020-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0020_auto_20200613_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='contratante',
            field=models.ManyToManyField(related_query_name='+', to='core.Contratante'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='polo_atuacao',
            field=models.ManyToManyField(related_query_name='+', to='core.PoloAtuacao'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_query_name='+', to='core.Servico'),
        ),
    ]
