# Generated by Django 2.2 on 2020-06-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0021_auto_20200613_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='polo_atuacao',
        ),
    ]
