# Generated by Django 2.2 on 2020-06-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0024_auto_20200614_2008'),
        ('edital', '0022_remove_edital_polo_atuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Inabilitada'), ('2', 'Habilitada'), ('3', 'Expirada'), ('4', 'Descredenciada')], default='0', max_length=100, verbose_name='Status geral')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital.Edital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
