# Generated by Django 2.2 on 2020-06-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0025_auto_20200615_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentorequisitoinscricao',
            options={'verbose_name': 'Documento Requisitado', 'verbose_name_plural': 'Documentos Requisitados'},
        ),
        migrations.RemoveField(
            model_name='documentorequisitoinscricao',
            name='edital',
        ),
    ]
