# Generated by Django 2.2 on 2020-06-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0026_auto_20200615_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorequisitoinscricao',
            name='status',
            field=models.CharField(choices=[('0', 'Em Análise'), ('1', 'Inabilitado'), ('2', 'Habilitado')], default='0', max_length=100, verbose_name='Status do Documento'),
        ),
    ]
