# Generated by Django 2.2 on 2020-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0032_auto_20200615_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
