# Generated by Django 2.2 on 2020-06-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200613_1835'),
        ('edital', '0033_auto_20200615_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorequisitoinscricao',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Servico'),
        ),
    ]
