# Generated by Django 2.2 on 2020-06-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0034_documentorequisitoinscricao_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorequisitoinscricao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
