# Generated by Django 2.2 on 2020-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0037_documentorequisitoinscricao_titulo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorequisitoinscricao',
            name='titulo_documento',
            field=models.CharField(editable=False, max_length=250, null=True, verbose_name='Título do Documento'),
        ),
    ]
