# Generated by Django 2.2 on 2020-06-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200616_1831'),
        ('edital', '0038_auto_20200616_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentorequisitoinscricao',
            name='titulo_documento',
        ),
        migrations.AddField(
            model_name='documentorequisitoinscricao',
            name='requisito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Requisito'),
        ),
    ]
