# Generated by Django 2.2 on 2020-06-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0041_auto_20200618_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorequisitoinscricao',
            name='inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edital.Inscricao'),
        ),
        migrations.AlterField(
            model_name='documentorequisitoinscricao',
            name='requisito',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Requisito'),
        ),
        migrations.AlterField(
            model_name='documentorequisitoinscricao',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Servico'),
        ),
    ]
