# Generated by Django 2.2 on 2020-06-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_documentousuario'),
        ('edital', '0044_auto_20200619_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='documentos_usuario',
            field=models.ManyToManyField(to='core.DocumentoUsuario'),
        ),
    ]
