# Generated by Django 2.2 on 2020-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_documentousuario'),
        ('edital', '0045_inscricao_documentos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='documentos_usuario',
        ),
        migrations.AddField(
            model_name='edital',
            name='documentos_usuario',
            field=models.ManyToManyField(related_query_name='+', to='core.DocumentoUsuario'),
        ),
    ]
