# Generated by Django 2.2 on 2020-06-19 11:48

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0046_auto_20200619_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUsuarioInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Em Análise'), ('1', 'Documento OK'), ('2', 'Documento Vencido'), ('3', 'Documento Ilegível'), ('4', 'Documento Inválido')], default='0', max_length=100, verbose_name='Status do Documento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('documento', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Documento Pessoal do Usuário',
                'verbose_name_plural': 'Documentos Pessoais dos Usuários',
            },
        ),
    ]
