# Generated by Django 2.2 on 2020-06-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0047_documentousuarioinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentousuarioinscricao',
            name='inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edital.Inscricao'),
        ),
    ]
