# Generated by Django 2.2 on 2020-06-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_documentousuario_ordem'),
        ('edital', '0048_documentousuarioinscricao_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentousuarioinscricao',
            name='DocumentoUsuario',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DocumentoUsuario'),
        ),
    ]
