# Generated by Django 2.2 on 2020-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0049_documentousuarioinscricao_documentousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='edital',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
