# Generated by Django 2.2 on 2020-06-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0050_auto_20200619_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentousuarioinscricao',
            old_name='DocumentoUsuario',
            new_name='documento_usuario',
        ),
    ]
